src/lib/api/transform.spec.ts, src/lib/api/transform.ts
Transformations bugfix
- fix torn_edges transformation
- add audio/video transformation
=> fix(transform) Fix some validators in transforms, Add video transforms

package-lock.json, package.json
=> fix(ie11): downgrade atob lib

src/lib/api/upload/network.ts, src/lib/api/upload/types.ts, src/lib/api/upload/upload.spec.ts, src/lib/api/upload/upload.ts
=> feat(workflows): Add support for workflows

src/lib/picker.ts
=> fix(pickerOptions/workflows): Fix workflowIds name in options

src/lib/api/upload/network.ts
Add policy and signature to complete event. Required for workflows
=> fix(upload): add signature and policy to complete upload event

karma.conf.js
Bump edge version in karma config to latest
=> test(browserstack): run tests on newest edge version

package.json, src/lib/api/upload/file_utils.ts, src/lib/api/upload/upload.ts
Fix problems with file partitioning during upload
=> fix(upload): fix problems with file partitioning

src/config.ts
Fix promlems with picker:
- fix(Translate): Fix custom translations in errors
- fix(thumbnails): Local thumbnails are rotated corectly (according to exif) 
- Add upload more button
- feat(opentok): Update opentalk to newest version
- Fix some minor issues
=> feat(picker): Update picker version

src/lib/api/transform.ts, src/schema/transforms.schema.spec.ts, src/schema/transforms.schema.ts
Add new transforms to filestack-js pdfinfo and pdfconvert
=> feat(transforms): add pdfinfo and pdfconvert to transforms

src/config.ts
Disable uploadInBackground when cropper is enabled
=> refactor(picker): Disable uploadInBackground when cropper is enabled

src/config.ts, src/lib/picker.ts
Add tr language support in picker
=> feat(picker): Add tr language pack to picker

src/config.ts, src/lib/filelink.ts, src/schema/transforms.schema.ts
Update
Update picker version to 1.4.6
=> chore(config): update picker version

README.md, src/config.ts, src/lib/picker.ts
New version of picker contains changes to satisfy google ux review
=> feat(config): Update version of picker

src/lib/picker.ts, src/schema/picker.schema.ts
- Update picker interface
- Update picker options schema
=> feat(picker): Update picker interface

src/lib/api/cloud.spec.browser.ts, src/lib/api/cloud.ts
=> fix(cloud): fix cloud urls

src/config.ts
=> chore(config): Update picker

package-lock.json, src/config.ts, src/lib/api/cloud.spec.browser.ts, src/lib/api/cloud.ts
Picker- Fix problems with opentok
=> fix(picker): Fix opentok integration

package-lock.json, package.json, src/config.ts, src/lib/api/upload/uploaders/s3.ts, src/lib/client.ts, src/lib/picker.ts
Picker
- Add onFileCropped callback
- Fix Italian translation in picker
Sdk
- Set apikey as tag in sentry
- Update some error messages
=> feat(picker): Add onFileCropped callback

package-lock.json, src/lib/api/upload/uploaders/s3.spec.ts, src/lib/api/upload/uploaders/s3.ts
Display proper error message when etag field is missing in s3 response (probably not exposed in cors)
=> feat(uploader/s3): Regular upload - s3 error handling

src/lib/filelink.ts, src/schema/transforms.schema.ts
Update enhance transform with new options
=> feat(transforms): Update enhance preset definition

src/config.ts
Fix problem with vailidation in onFileSelected in picker
=> fix(picker): fix onFileSelected problem

manual_tests/upload_new.ts, src/lib/api/upload/uploaders/s3.spec.ts, src/lib/api/upload/uploaders/s3.ts, src/lib/filelink.ts
Add disableStorageKey to client
=> feat(s3): add disable store key to uplaoder

src/config.ts, src/lib/picker.ts
- Fix problems with video black frame in picker
- Add missing translation to dropPane
=> feat(picker): bump picker version to 1.11.1

src/lib/client.ts
=> chore(fix): error on

src/lib/api/cloud.spec.browser.ts, src/lib/api/cloud.ts
Add mimetype filtering in clouds api
=> feat(clouds): add mimetype filtering in clouds

CHANGELOG.md, package-lock.json, package.json, src/lib/api/upload/uploaders/s3.ts
Fix complete request target for s3 uploader
=> fix(s3/complete): fix target for complete request

CHANGELOG.md, package-lock.json, package.json, src/lib/api/cloud.spec.browser.ts, src/lib/api/cloud.ts, src/lib/utils/store.browser.ts, src/lib/utils/store.node.ts, src/lib/utils/store.ts
Allow cloud token bo be stored in avalaible browser store only, if all stores are blocket so suppres error message
=> feat(clouds): add store adapter for better localstore/sessionstore support

src/lib/client.ts, src/lib/request/adapters/http.ts, src/lib/utils/extensions.ts, src/lib/utils/index.spec.ts, src/lib/utils/index.ts
=> feat(utils): add converting extension to mimetype

scripts/publish.js
Fix problem with deployment variable
=> fix(publish): fix error in publis script

CHANGELOG.md, manual_tests/request.ts, package-lock.json, package.json, scripts/publish.js, src/config.ts, src/lib/api/file.spec.ts, src/lib/api/file.ts, src/lib/client.ts, src/lib/request/adapters/xhr.ts, src/lib/request/types.ts
Mark retrieve method as deprecated - use download or metadata instead
=> feat(download): Add download file method

README.md
=> docs(ie11): remove id11 badge and add support note

src/lib/api/store.spec.ts, src/lib/api/store.ts, src/lib/client.spec.ts, src/lib/client.ts
=> fix(storeurl): support for workflows to storeURL

.github/workflows/deploy.yml, package.json, scripts/publish.js
Fix some minor problems in deployment script
=> fix(deploy): fix deployment script

manual_tests/client.js, src/schema/definitions.schema.ts
=> fix(schema-validation): disable bucket region validation

src/lib/picker.ts
=> docs(PickerOptions): add unsplash to PickerOptions allowed sources

src/lib/picker.ts, src/schema/picker.schema.ts
=> docs(picker): change source picasa to googlephotos

src/lib/api/upload/upload.ts, src/lib/api/upload/uploaders/s3.ts, src/lib/client.ts, src/lib/picker.ts
=> feat(upload): emit event on file upload start

src/schema/picker.schema.ts
=> feat(picker): support callback for tags

src/lib/picker.ts, src/schema/picker.schema.ts
=> feat(picker): Picker paste event add configuration options

src/lib/api/upload/file.ts, src/lib/api/upload/uploaders/abstract.ts, src/lib/api/upload/uploaders/s3.ts
I have created this PR to fix https://filestack.atlassian.net/browse/FS-10615. Please review the same.
=> FS-10615 - Allow upload files bigger than 50GB

CHANGELOG.md, package-lock.json, package.json, src/config.ts, src/lib/request/helpers/data.ts, src/lib/utils/index.spec.ts, src/lib/utils/index.ts
Ensured resolveHost is idempotent to fix cases where the cname is replaced more times
=> Ensured resolveHost is idempotent

src/lib/utils/index.ts
=> fix zip bug with accept

src/lib/utils/index.ts
=> handle some PNG files when resized

CHANGELOG.md, package-lock.json, package.json, src/lib/utils/extensions.ts
Bug fix
Error when `vsdx` accept option added
> https://filestack.atlassian.net/browse/FS-11598
Fixed
=> fix:(FS-11598: handle support for vsdx accept option)

README.md
README.md file updated
Removed polyfill.io URL reference as it's vulnerable
It's not a feature change
=> [FS-1816] Remove polyfill.io reference in Readme

src/lib/picker.ts, src/schema/picker.schema.ts
=> FS-11959: add disableAltText option

package-lock.json, package.json
Updated the file type package to latest version. As the existing version was not able to detect the correct mime type
=> [FS-12179] Updated the file type package

package-lock.json, package.json, src/lib/utils/index.ts
Fixed import fileType buffer method issue
=> [12179] Fixed import fileType buffer method issue
