README.md
The old `maxSize` showed `10*1024*1024` as `1MB` but it is actually `10MB`.
=> Fix `maxSize` example

.eslintrc, config/env_production.js, lib/index.js, rollup.config.js, rollup_cdn.config.js
Issue is, that when you run .pick with custom CNAME set, everything gets downloaded from your CNAME except for picker-xx.js file, and some additional files downloaded by that library (like main.css).
This fix resolves this, it results in all files being downloaded from the CNAME
=> Add support for CNAME for static picker files

src/config.ts
Fix bug in picker connected with cnames - assets was loading from wrong domain filestackapi.com when cname was provided
=> fix(picker/cname): Load assets from correct cname - picker v1.2.2

src/lib/api/upload/network.ts, src/lib/api/upload/types.ts, src/lib/api/upload/upload.spec.ts, src/lib/api/upload/upload.ts, src/lib/client.ts, src/lib/picker.ts
Move workflows ids to storeOptions
Add workflows support for store method
=> feat(workflows): Add workflows ids to store options

README.md
Docs update
Http links work, but are not taking advantage of the latest best practice on the web.
No change to behavior; only updated links in the README file.
I tested each link in my browser to confirm that they are valid and work as before.
=> Changing http to https in readme links

src/lib/api/security.ts
Fix policy validator - call signature allows array instead of string
=> fix(security): fix call validator

package-lock.json, package.json
Downgrade atob lib again to support filestack in ie11
IE11 cannot parse template literals, so filestack.js crashes.
filestack.js runs on IE11
=> fix(ie11) downgrade atob lib again

src/lib/filelink.ts
- Add possibility to disable validation 
- Use validator as static prop
=> feat(filelink): Add able to switch of validation on task params

src/lib/filelink.ts, src/lib/utils/index.spec.ts, src/lib/utils/index.ts
Update b64 to support url-safe string
=> fix(base64): Fix b64 url safe creation in filelink

src/lib/filelink.spec.ts, src/lib/filelink.ts
Add setSource method to filelink class
=> feat(filelink): add set soruce method

src/lib/filelink.spec.ts, src/lib/filelink.ts, src/schema/transforms.schema.ts
=> feat(transforms): Add autoImage transformation

README.md
Bug fix
The picker fails under IE11 with the current polyfill:
`object doesn't support method or property 'includes'`
Adding String.prototype.includes seems to fix it.
=> Add String.prototype.includes to polyfill

README.md, webpack.config.js
Remove gzip from build scripts, use cdn in-fly gzip mechanism
=> build(gzip): Remove gzip script, use cdn in-fly gzip feature

README.md, package-lock.json, package.json, src/lib/client.ts
* **What kind of change does this PR introduce?**
Bug fix
See https://github.com/filestack/filestack-js/issues/416
`Sentry.configureScope` is no longer invoked in hopes this fixes Sentry application context issues
=> fix(sentry): remove discouraged configureScope

package.json
Bug fix
See #416 
Use Sentry's v6.1.0 (from v6, the `hub.startSession` is used)
=> [Fix] (sentry-416): use Sentry v6 version

src/lib/utils/extensions.ts
**Bugfix**
Currently `.avi` files were not properly validated even when in `accept` array, .avi extension has been placed. This change is fixing this issue by modifying **ExtensionMap** const key for avi file extension. 
While using file-type library for checking mime type of files, there is a need to apply the same value of returned mime-type (https://github.com/sindresorhus/file-type/blob/v10.11.0/index.js#L345)
=> fix(extensions): Changed avi format for assertion purpose

src/lib/picker.ts, src/schema/picker.schema.ts
This change adds validation schema for new default text feature introduced for image search.
The following properties have been introduced for the same:
websearch: {
predefinedText: 'Sample text'
}
=> Validation schema added for default image search

src/lib/api/transform.ts, src/lib/filelink.ts, src/schema/transforms.schema.ts
It adds audio_codec parameter to video_convert in TransformOptions
* **What is the current behavior?**
video_convert in TransformOptions does not have audio_codec parameter 
https://filestack.atlassian.net/browse/FS-10439
video_convert in TransformOptions can receive audio_codec parameter with any of the values listed here
https://www.filestack.com/docs/api/video_processing/#audio-transcoding-options
Manual test:
https://drive.google.com/file/d/1yk5EF5zMBWF4FuVHRPLpHsLEdGCcMbr2/view?usp=sharing
Rebased to the branch with latest packages and ran tests:
=> Added parameter for audio_codec in VideoConvertParams

package-lock.json, package.json, src/lib/request/helpers/data.ts
It's a security upgrade based on https://github.com/filestack/filestack-js/pull/518 . Dependabot did the version bump and then I fixed the tests.
Currently there are a few CVEs asking for an upgrade of the fast-xml-parser package.
Based on the tests, it works as before, but without the security warnings.
* https://github.com/advisories/GHSA-6w63-h3fj-q4vw
* https://github.com/advisories/GHSA-x3cc-x39p-42qx
=> Bump fast-xml-parser

src/lib/api/upload/uploaders/s3.spec.ts
What kind of change does this PR introduce?
- Redundant unit test cases removed.
What is the current behavior?
- Chunk size was static so, parts calculation was done according to the static values
What is the new behavior (if this is a feature change)?
- Chunk size is dynamic , so parts calculation will differ here.
The above change was added in this commit earlier,
https://github.com/filestack/filestack-js/pull/516/files
=> Redundant test cases removed as per new chunk size calculation

src/lib/utils/index.ts
Bug fix -  Added fallback type as application/octet-stream
No fallback for file type
Added fallback type as application/octet-stream
=> fix: [FS-11598] Added fallback type as application/octet-stream

.github/workflows/deploy_stage.yml, package.json, scripts/cache.js, scripts/publish.js, src/config.ts, src/lib/utils/extensions.ts, src/lib/utils/index.ts
fix
hpt file type mime returns as plain/text
hpt file type mime returns as application/octet-stream
=> Fixed support for hpt file type and added stage CI/CD pipeline.

src/lib/client.ts
- No additional configuration, such as `Sentry.captureException()` on the client-side application, is required to display the upload error logs in the Sentry dashboard.
- The issue has been resolved by implementing [withScope](https://docs.sentry.io/platforms/javascript/best-practices/multiple-sentry-instances/#using-withscope-with-multiple-clients) and `scope.captureException(e)`
=> Sentry issue 
